title: Hugo Netlify Starter

disableKinds:
  - taxonomy
  - taxonomyTerm

enableGitInfo: true

caches:
  assets:
    dir: ':cacheDir/_gen'
    maxAge: -1
  getcsv:
    dir: ':cacheDir/:project'
    maxAge: 60s
  getjson:
    dir: ':cacheDir/:project'
    maxAge: 60s
  images:
    dir: ':cacheDir/_images'
    maxAge: -1
  modules:
    dir: ':cacheDir/modules'
    maxAge: -1

markup:
  highlight:
    style: paraiso-dark

params:
  projectName: Hugo Netlify Starter
  font_awesome_version: 5.12.0
  description: Boilerplate for building beautiful websites
  favicon: favicon.png
  repositoryUrl: 'https://github.com/cncf/hugo-netlify-starter'
  contentDir: /content/
  logos:
    navbar: cncf-color.png
  social:
    - name: GitHub
      color: '#000000'
      url: 'https://github.com/cncf/hugo-netlify-starter'
      icon: fab fa-github
    - name: Twitter
      color: '#00aced'
      url: 'https://twitter.com/CloudNativeFdn'
      icon: fab fa-twitter
  fonts:
    - name: Roboto
      sizes:
        - 400
        - 500
        - 700
      type: heading_font
    - name: Open Sans
      sizes:
        - 400
        - 600
        - 700
      type: sans_serif

menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: Documentation
      url: /en/docs/
      weight: 2


# Internationalization

defaultContentLanguage: en

# show language abbreviation in url. If you enable this option, remember to update image paths
# defaultContentLanguageInSubdir: true
languages:
  ar:
    contentDir: content/ar
    languageName: عربى
    languagedirection: rtl
    title: مدونتي
    weight: 2
  en:
    contentDir: content/en
    languageName: English
    title: My project
    weight: 1
  esp:
    contentDir: content/spa
    languageName: Español
    title: Mi proyecto
    weight: 2
  fr:
    contentDir: content/fr
    languageName: Français
    title: Mon projet
    weight: 2
  pt-pt:
    contentDir: content/pt
    languageName: Português
    title: O meu blog
    weight: 3
